(borrow check failure)
    error[E0500]: closure requires unique access to `stripped_line` but it is already borrowed
       --> src/item.rs:489:35
        |
    477 | pub fn read_item<'t>(fileno: u16,
        |                  -- lifetime `'t` defined here
    ...
    484 |         let commentless_line = stripped_line.colstr();
        |                                ----------------------
        |                                |
        |                                borrow occurs here
        |                                argument requires that `*stripped_line` is borrowed for `'t`
    ...
    489 |             while peeking(source, |linenum, line| {
        |                                   ^^^^^^^^^^^^^^^ closure construction occurs here
    490 |                 copy_line_stripping_comments(fileno, linenum, line,
    491 |                                              stripped_line)?;
        |                                              ------------- second borrow occurs due to use of `stripped_line` in closure

    error[E0500]: closure requires unique access to `stripped_line` but it is already borrowed
       --> src/item.rs:525:39
        |
    477 | pub fn read_item<'t>(fileno: u16,
        |                  -- lifetime `'t` defined here
    ...
    484 |         let commentless_line = stripped_line.colstr();
        |                                ----------------------
        |                                |
        |                                borrow occurs here
        |                                argument requires that `*stripped_line` is borrowed for `'t`
    ...
    525 |                 while peeking(source, |linenum, line| {
        |                                       ^^^^^^^^^^^^^^^ closure construction occurs here
    526 |                     copy_line_stripping_comments(fileno, linenum, line,
    527 |                                                  stripped_line)?;
        |                                                  ------------- second borrow occurs due to use of `stripped_line` in closure

    error[E0597]: `stripped_line` does not live long enough
       --> src/item.rs:527:50
        |
    477 | pub fn read_item<'t>(fileno: u16,
        |                  -- lifetime `'t` defined here